# Generated by Django 4.2.3 on 2023-07-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astro", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="diffculty", new_name="difficulty",
        ),
    ]
