# Generated by Django 4.2.3 on 2023-08-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astro", "0002_rename_diffculty_question_difficulty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qusers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="username")),
                (
                    "totalpoints",
                    models.BigIntegerField(default=0, verbose_name="totalpoints"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
        ),
    ]
