# Generated by Django 4.2.3 on 2023-09-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astro", "0003_qusers"),
    ]

    operations = [
        migrations.RemoveField(model_name="qusers", name="id",),
        migrations.AddField(
            model_name="question",
            name="optional_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="optional_images/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="qusers",
            name="username",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                verbose_name="username",
            ),
        ),
    ]
