# Generated by Django 4.2.3 on 2023-09-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astro", "0004_remove_qusers_id_question_optional_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="optional_image",
            field=models.BinaryField(blank=True, null=True, verbose_name="Image"),
        ),
    ]
